source "https://rubygems.org"
ruby '2.2.2'

gem "ruboty"
gem "ruboty-alias"
gem "ruboty-cron"
gem "ruboty-google_image"
gem "ruboty-slack"
gem 'ruboty-maekawa',
    github: "mopp/ruboty-maekawa"
gem 'ruboty-lgtm',
    github: "kanmi/ruboty-lgtm"
gem "calil",
    github: "mopp/calil",
    branch: "add_libkey"
gem 'ruboty-tumblr_image',
    github: "hogelog/ruboty-tumblr_image"
gem 'ruboty-repeat',
    github: "kanmi/ruboty-repeat"
gem 'ruboty-scorekeeper',
    github: "yoshiori/ruboty-scorekeeper"
gem 'ruboty-misawa',
    github: "mzp/ruboty-misawa"
gem 'ruboty-zoi',
    github: "makimoto/ruboty-zoi"
gem 'ruboty-response',
    github: "kaihar4/ruboty-response"
